[tox]
envlist = py38,py39,py310,py311
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    black
    pylint
commands =
    pytest --cov=src tests/
    black --check src tests
    pylint src tests

[testenv:format]
deps = black
commands = black src tests

[testenv:lint]
deps = pylint
commands = pylint src tests 